name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stylua - format Lua (non-blocking)
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .

      - name: ShellCheck (errors only)
        continue-on-error: true
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck
          shellcheck -S error install.sh || true
          if ls scripts/*.sh >/dev/null 2>&1; then shellcheck -S error scripts/*.sh || true; fi

